services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: dev
        USER_UID: 1000
        USER_GID: 1000
    container_name: jupyterlab
    user: dev
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    working_dir: /code
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
